const RICKAVDMORTYAPI_ROOT = 'https://rickandmortyapi.com/api/';
const RICKAVDMORTYAPI_CHARACTER = 'character';
const RICKAVDMORTYAPI_PAGE = '/?page=';

export const API_CHARACTER_WITHPAGE = RICKAVDMORTYAPI_ROOT+RICKAVDMORTYAPI_CHARACTER+RICKAVDMORTYAPI_PAGE;
export const API_CHARACTER = RICKAVDMORTYAPI_ROOT+RICKAVDMORTYAPI_CHARACTER;